sudo: required
dist: xenial
language: python
cache: pip
before_install:
- if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo sudo apt-get update; fi
install:
- pip install coverage coveralls flake8 flake8-bugbear mypy
- pip install -e .
script:
- sudo mkdir -p /black
- sudo mount --bind $(pwd) /black
- coverage run /black/tests/test_black.py
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then mypy black.py tests/test_black.py; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.6-dev' ]]; then flake8 black.py tests/test_black.py; fi
after_success:
- coveralls
notifications:
  on_success: change
  on_failure: always
matrix:
  include:
    - python: 3.6
    - python: 3.6-dev
    - python: 3.7-dev
